[book]
authors = ["Ether-Rust Core Contributors"]
language = "en"
multilingual = false
src = "book"
title = "Ether-Rust Book"
description = "A book on all things Ethereum-Rust"

[output.html]
theme = "book/theme"
git-repository-url = "https://github.com/VersoriumX-Technology/Ether-Rust"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "target/book"

[preprocessor.template]
before = ["links"]

[preprocessor.index]

[preprocessor.links]
