# VersoriumX-Technology Configuration

[database]
# Database connection settings
url = "postgres://user:password@localhost/versoriumx_db"
pool_size = 10  # Number of database connections in the pool

[logging]
# Logging configuration
level = "info"  # Log level (e.g., debug, info, warn, error)
file = "versoriumx.log"  # Log file path

[api]
# API configuration
key = "your_api_key_here"  # API key for external services
timeout = 30  # Timeout for API requests in seconds

[network]
# Network settings for VersoriumX-Technology
optimism_rpc_url = "https://optimism-mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID"
starknet_rpc_url = "https://starknet-mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID"
ethereum_rpc_url = "https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID"

[features]
# Feature flags for enabling/disabling specific functionalities
enable_feature_x = true
enable_feature_y = false

[environment]
# Environment settings
mode = "production"  # Can be "development", "staging", or "production"
version = "1.0.0"  # Application version
[alias]
docs = "doc --workspace --all-features --no-deps"

[target.x86_64-pc-windows-msvc]
rustflags = [
    # Increases the stack size to 10MB, which is
    # in line with Linux (whereas default for Windows is 1MB)
    "-Clink-arg=/STACK:10000000",
]

[target.i686-pc-windows-msvc]
rustflags = [
    # Increases the stack size to 10MB, which is
    # in line with Linux (whereas default for Windows is 1MB)
    "-Clink-arg=/STACK:10000000",
]
